#!/bin/zsh

if [ $# -eq 0 ]; then
    echo "Usage: ${0:t} FILES"
    exit 1
fi

for path in "$@"; do
    if [ ! -e "$path" ]; then
        echo "Error: '$path' does not exist" >&2
        exit 1
    fi
done

sudo chown -R "$USER" -- "$@"
