# Icons for l command (nerd font icons)
default = ""
symlink = ""
symlink_dir = ""
symlink_exec = ""
symlink_file = ""
directory = ""
current_dir = ""
executable = ""
file = ""
git_modified = ""
git_untracked = "󰛑"
git_staged = ""
git_deleted = ""
readonly = ""
[extensions]
