#!/usr/bin/env zsh

PARENT=${0:A:h}
source $PARENT/common

DIRS=("$SCDIR" "$DLDIR" "$HOME/.trash")

total-size() {
  du -hscL $@ | tail -n1 | awk '{print $1}'
}

size=$(total-size "${DIRS[@]}")
echo "The following ($size) will be removed:"
for dir in "${DIRS[@]}"; do
  l --depth 2 "$dir"
done
echo -n "Are you sure? (y/n): "
read choice
case "$choice" in
    y|Y|yes|YES ) ;;
    * ) echo "Aborting."; return 1;;
esac
for dir in "${DIRS[@]}"; do
  rm -rf "$dir"/*(N)
done
