#!/usr/bin/env zsh

SCRIPT_DIR="${0:A:h}"
source "$SCRIPT_DIR/common"

if [ $# -eq 0 ]; then
    echo "Usage: ${0:t} FILES"
    exit 1
fi

for path in "$@"; do
    if [ ! -e "$path" ]; then
        error "'$path' does not exist"
    fi
done

/usr/bin/sudo /bin/chown -R "$USER" -- "$@"
